/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package cascading.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TestEnum { 
  ONE, TWO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TestEnum\",\"namespace\":\"cascading.avro\",\"symbols\":[\"ONE\",\"TWO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
